### ISSUE TITLE
Releases are not indexed

### ISSUE THREAD

**Issue by Tux** [haje61/Tk-Contrib#1]
`$ cpan Tk::Contrib`

is not going to work, sadly, as the release does not contain a `Tk::Contrib` module, so you wouldn't be able to install via that name. You (user `HANJE`) does not have permissions on `Tk::Contrib`, which is required for PAUSE to index a release with that name.

FWIW, I'd love to play with it

**Comment by haje61** [comment]
I am supposed to have adopted this package. Something about that
does not seem to be straight forward. Should I include a Contrib.pm just for 
the sake of it being indexed?

**Comment by Tux** [comment]
Maybe. I am no PAUSE expert. If you have IRC, please join #toolchain or #metacpan on irc.perl.org
People over there can tell all you need to know, and some are able to "fix" issues in the actual database

Thanks for taking up Tk issues BTW, really appreciate it!

**Comment by haje61** [comment]
Neil Bowers resolved it.
Happy playing!

Hans
